[package]
name = "trading-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
trading_strategies = { path = "../trading-strategies" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"