[package]
name = "trading-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
trading_strategies = { path = "../trading-strategies", features = ["moving-average", "tick-support"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"